clients/urls.py
from django.urls import path
from .views import ClientListView

app_name = 'clients'

urlpatterns = [
    path('', ClientListView.as_view(), name='client_list')
]

orders/urls.py
from django.urls import path

from orders.views import OrderListView, OrderCreateView

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='order_list'),
    path('create/', OrderCreateView.as_view(), name='order_create')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_redirect_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home_redirect_view),
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('orders/', include('orders.urls'), name='orders'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clients/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField('Имя', max_length=150)
    lastname = models.CharField('Фамилия', max_length=150)
    phone = models.CharField('Телефон', max_length=15, blank=True)
    telegram = models.CharField('Telegram', max_length=100, blank=True)
    vk = models.CharField('Вк', max_length=150, blank=True)
    problem_client = models.BooleanField('Проблемный клиент', default=False)

    def __str__(self):
        return f'{self.lastname} {self.name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

orders/models.py
from django.db import models


class Order(models.Model):
    client = models.ForeignKey('clients.Client', related_name='orders', on_delete=models.PROTECT, verbose_name='Клиент')
    closed = models.BooleanField('Закрыт', default=False)
    title = models.CharField('Название', max_length=300)
    description = models.TextField('Описание', blank=True, max_length=5000)
    start_time = models.DateField('Дата начала заказа', auto_now_add=True)
    deadline = models.DateField('Дедлайн')
    payed = models.BooleanField('Оплачен', default=False)
    status = models.ForeignKey(
        'Status',
        related_name='orders',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Статус'
    )

    def __str__(self):
        return f'{self.client}: {self.title}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class SubTask(models.Model):
    title = models.CharField('Название', max_length=300)
    done = models.BooleanField('Завершено', default=False)
    order = models.ForeignKey('Order', related_name='subtasks', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Подзадача'
        verbose_name_plural = 'Подзадачи'


class Status(models.Model):
    title = models.CharField('Название', max_length=150)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

orders/forms.py
from django import forms
import django_select2.forms as select2_forms
from . import models


class SubTaskForm(forms.ModelForm):
    class Meta:
        model = models.SubTask
        fields = ['title', 'done']
        widgets = {
            'done': forms.CheckboxInput(attrs={'class': 'checkboxinput form-check-input'})
        }


class OrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = models.Order
        widgets = {
            'client': select2_forms.Select2Widget(),
            'status': select2_forms.Select2Widget(),
            'deadline': forms.SelectDateWidget()
        }
        fields = ('title', 'status', 'client', 'description', 'deadline', 'closed', 'payed')

clients/views.py
from django.views.generic import ListView
from .models import Client


class ClientListView(ListView):
    model = Client
    template_name = 'clients/ClientList.html'

orders/views.py
from django.urls import reverse
from django.views.generic import ListView
from extra_views import CreateWithInlinesView, InlineFormSetFactory
from .models import Order, SubTask
from .forms import OrderForm, SubTaskForm


class OrderListView(ListView):
    model = Order
    template_name = 'orders/OrderList.html'


class SubTaskInline(InlineFormSetFactory):
    model = SubTask
    form_class = SubTaskForm
    factory_kwargs = {
        'extra': 0
    }


class OrderCreateView(CreateWithInlinesView):
    model = Order
    template_name = 'DetailForm.html'
    form_class = OrderForm
    inlines = [SubTaskInline]

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Создать заказ'
        context_data['model_name'] = 'Order'
        return context_data

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if not kwargs.get('initial'):
            kwargs['initial'] = {}
        return kwargs

    def get_success_url(self):
        return reverse('orders:order_list')

    def form_invalid(self, form):
        return super().form_invalid(form)

project/views.py
from django.urls import reverse
from django.shortcuts import redirect


def home_redirect_view(request):
    return redirect(reverse('orders:order_list'))

clients/templates/clients/ClientList.html
{% extends 'base.html' %}
{% block title %}Список клиентов{% endblock %}
{% block before_content %}
<div class="container mt-3">
    <div class="d-flex flex-wrap justify-content-lg-end">
        <a class="btn btn-primary" href="#">Добавить клиента</a>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="mt-2 mb-2 w-100 p-3">
    {% if client_list %}
    <div class="table-responsive">
        <table class="table text-md-nowrap table_with_sorting">
            <thead>
            <tr>
                <th>Id</th>
                <th>Имя Фамилия</th>
                <th>Телефон</th>
                <th>Телеграм</th>
                <th>Проблемный клиент</th>
                <th>Количество проектов</th>
            </tr>
            </thead>
            <tbody>
            {% for client in client_list %}
            <tr>
                <td>{{ client.id }}</td>
                <td class="w-25">
                    <a href="{{ client.get_absolute_url }}">
                        {{ client.name }} {{ client.lastname }}
                    </a>
                </td>
                <td>{{ client.phone }}</td>
                <td><a href="#">{{ client.telegram }}</a></td>
                <td><img src="/static/admin/img/{% if client.problem_client %}icon-yes{% else %}icon-no{% endif %}.svg" alt="{{ client.problem_client }}"></td>
                <td><a href="#">{{ client.orders.count }}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    Клиентов нет
    {% endif %}
</div>
{% endblock %}

orders/templates/orders/OrderList.html
{% extends 'base.html' %}
{% block title %}Список заказов{% endblock %}
{% block before_content %}
<div class="container mt-3">
    <div class="d-flex flex-wrap justify-content-lg-end">
        <a class="btn btn-primary" href="{% url 'orders:order_create' %}">Создать заказ</a>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="mt-2 mb-2 w-100 p-3">
    {% if order_list %}
    <div class="table-responsive">
        <table class="table text-md-nowrap table_with_sorting">
            <thead>
            <tr>
                <th>Id</th>
                <th>Название</th>
                <th>Клиент</th>
                <th>Статус</th>
                <th>Закрыт</th>
                <th>Оплачен</th>
                <th>Дедлайн</th>
            </tr>
            </thead>
            <tbody>
            {% for order in order_list %}
            <tr>
                <td>{{ order.id }}</td>
                <td class="w-25">
                    <a href="{{ order.get_absolute_url }}">
                        {{ order.title }}
                    </a>
                </td>
                <td>
                    {{ order.client }}
                </td>
                <td>
                    {{ order.status }}
                </td>
                <td><img src="/static/admin/img/{% if order.closed %}icon-yes{% else %}icon-no{% endif %}.svg" alt="{{ order.closed }}"></td>
                <td><img src="/static/admin/img/{% if order.payed %}icon-yes{% else %}icon-no{% endif %}.svg" alt="{{ order.payed }}"></td>
                <td>{{ order.deadline }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    Заказов нет
    {% endif %}
</div>
{% endblock %}

orders/templates/orders/SubTaskInlines.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}


{% with inlines.0 as formset %}
{% with formset.prefix as formset_prefix %}
<div class="border border-light p-3">
    <div class="scrollbar" id="{{ formset_prefix }}_scrollbar">

        {{ formset.management_form }}

        {% for form in formset.forms %}
        <div>
            <div class="row mb-3">
                {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
                {% endfor %}
                <div class="row">
                    <div class="col-2">{{ form.done|as_crispy_field }}</div>
                    <div class="col-8">
                        {{ form.title }}
                    </div>
                    <div class="col-2">{{ form.DELETE|as_crispy_field }}</div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{#empty_form Start#}
{% with formset.empty_form as empty_form %}
<div id="{{ formset_prefix }}_empty_form" style="display:none">
    <div id="added_{{ formset_prefix }}-__prefix__-HIDE">
        <div class="row mb-3">
            {% for hidden_field in empty_form.hidden_fields %}
            {{ hidden_field }}
            {% endfor %}

            <div class="row">
                <div class="col-2">{{ inlines.0.empty_form.done|as_crispy_field }}</div>
                <div class="col-8">
                    {{ inlines.0.empty_form.title|as_crispy_field }}
                </div>
                <div class="col-2">
                    <div id="added_{{ formset_prefix }}-__prefix__-HIDE-btn"
                         onclick="hide_element('#added_{{ formset_prefix }}-__prefix__-HIDE')">
                        <button type="button" class="btn-close" aria-label="Close"></button>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
{% endwith %}
{#empty_form End#}

<div class="add-message-btn">
    <button
            type="button"
            class="pull-right btn btn-outline-primary mt-2"
            onclick="add_subtask()">
        Добавить подзадачу
    </button>
</div>
<script>
    function add_subtask() {
        let total_forms = $('#id_{{ formset_prefix }}-TOTAL_FORMS');
        let form_idx = total_forms.val();

        $('#{{ formset_prefix }}_scrollbar').append($('#{{ formset_prefix }}_empty_form').html().replace(/__prefix__/g, form_idx));
        total_forms.val(parseInt(form_idx) + 1);

        let block = document.getElementById("{{ formset_prefix }}_scrollbar");
        block.scrollTop = block.scrollHeight;
    }

</script>
{% endwith %}
{% endwith %}

templates/DetailForm.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<form method="post" class="m-3 p-3 w-100 bg-white" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mt-3 mb-3">
        <button type="submit" class="btn btn-success">Сохранить</button>
    </div>

    {% for field in form %}
    <div class="mb-2" w-100>
        {{ field|as_crispy_field }}
    </div>
    {% endfor %}

    {% if model_name == 'Order' %}
        {% include 'orders/SubTaskInlines.html' %}
    {% endif %}
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <script src="{% static 'js/base/hide_element.js' %}"></script>
</head>
<body>
    {% include 'header.html' %}
    <div class="before_content mt-3">
            {% block before_content %}{% endblock %}
    </div>
    <main class="container mt-2">
        <div class="bg-light">
            <div class="d-flex flex-wrap align-items-center justify-content-center">
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>
</body>
</html>

templates/header.html
<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <div class="container-fluid d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link text-white" aria-current="page" href="{% url 'orders:order_list' %}">
                            Заказы
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link text-white" aria-current="page" href="{% url 'clients:client_list' %}">
                            Клиенты
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Navbar -->
</header>